untested mods to install/uninstall scripts

diff --git a/install b/install
--- a/install
+++ b/install
@@ -43,16 +43,21 @@ fi
 #echo ""
 #echo Copying files	.
 
-RESULTS=`cp -rp * $LEO_LIB_DIR/ 2>&1`
-if [ $? -ne 0 ]; then
-    echo Failure copying files to $LEO_LIB_DIR
-    exit 1;
-fi
+# 7/29/08
+
+# # RESULTS=`cp -rp * $LEO_LIB_DIR/ 2>&1`
+# # if [ $? -ne 0 ]; then
+    # # echo Failure copying files to $LEO_LIB_DIR
+    # # exit 1;
+# # fi
 
 # Clean up the duplicate files.
 # Permissions were checked above.
-rm -rf $LEO_LIB_DIR/core
-rm -rf $LEO_LIB_DIR/config
+
+# 7/29/08
+
+# # rm -rf $LEO_LIB_DIR/core
+# # rm -rf $LEO_LIB_DIR/config
 
 # Copy the files
 cp -rp core $LEO_LIB_DIR/.
@@ -62,7 +67,7 @@ cp -rp config $LEO_LIB_DIR/.
 #echo ""
 #echo "Creating startup script located at: $LEO_RUN_SCRIPT_OUTPUT"
 
-echo "python ${LEO_PREFIX}/lib/core/runLeo.py \"$@\"" > $LEO_RUN_SCRIPT_OUTPUT
+echo "python ${LEO_PREFIX}/lib/leo/core/runLeo.py \"$@\"" > $LEO_RUN_SCRIPT_OUTPUT
 
 RESULTS=`chmod 755 $LEO_RUN_SCRIPT_OUTPUT`   
 
